name: Deploy LocalLang

# Run workflow on every push to the master branch
on:
  push:
    branches: [ release ]
    
jobs:
  deploy-locallang:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the release branch
    - uses: actions/checkout@v2
    
    # sets up .NET Core SDK
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.201
        
   # publishes Blazor project to the release-folder
    - name: Publish .NET Project
      run: dotnet publish LocalLangUI/LocalLangUI.csproj -c Release -o release --nologo
