//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalLangUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LabelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalLangUI.Resources.LabelResource", typeof(LabelResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидающие предложения.
        /// </summary>
        public static string AdminHeading {
            get {
                return ResourceManager.GetString("AdminHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string ApproveButton {
            get {
                return ResourceManager.GetString("ApproveButtoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все.
        /// </summary>
        public static string CategoryAll {
            get {
                return ResourceManager.GetString("CategoryAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string DetailsHeading {
            get {
                return ResourceManager.GetString("DetailsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выражение.
        /// </summary>
        public static string Expression {
            get {
                return ResourceManager.GetString("Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выражений.
        /// </summary>
        public static string ExpressionPlural {
            get {
                return ResourceManager.GetString("ExpressionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выражения.
        /// </summary>
        public static string ExpressionPlural2to4 {
            get {
                return ResourceManager.GetString("ExpressionPlural2to4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лайк.
        /// </summary>
        public static string LikeBottomText {
            get {
                return ResourceManager.GetString("LikeBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лайков.
        /// </summary>
        public static string LikeBottomTextPlural {
            get {
                return ResourceManager.GetString("LikeBottomTextPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лайкa.
        /// </summary>
        public static string LikeBottomTextPlural2to4 {
            get {
                return ResourceManager.GetString("LikeBottomTextPlural2to4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лайкнуть.
        /// </summary>
        public static string LikeTopText {
            get {
                return ResourceManager.GetString("LikeTopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Славечкi.
        /// </summary>
        public static string PageHeading {
            get {
                return ResourceManager.GetString("PageHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отказать.
        /// </summary>
        public static string RejectButton {
            get {
                return ResourceManager.GetString("RejectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск.
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Абв.
        /// </summary>
        public static string SortAlphabet {
            get {
                return ResourceManager.GetString("SortAlphabet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые.
        /// </summary>
        public static string SortNew {
            get {
                return ResourceManager.GetString("SortNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Популярные.
        /// </summary>
        public static string SortPopular {
            get {
                return ResourceManager.GetString("SortPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложение.
        /// </summary>
        public static string Submission {
            get {
                return ResourceManager.GetString("Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложений.
        /// </summary>
        public static string SubmissionPlural {
            get {
                return ResourceManager.GetString("SubmissionPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложения.
        /// </summary>
        public static string SubmissionPlural2to4 {
            get {
                return ResourceManager.GetString("SubmissionPlural2to4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить.
        /// </summary>
        public static string SuggestButton {
            get {
                return ResourceManager.GetString("SuggestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите категорию..
        /// </summary>
        public static string SuggestionCategoryDesctiption {
            get {
                return ResourceManager.GetString("SuggestionCategoryDesctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Какое выражение предложить?.
        /// </summary>
        public static string SuggestionExpressionDesctiption {
            get {
                return ResourceManager.GetString("SuggestionExpressionDesctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предложить выражение.
        /// </summary>
        public static string SuggestionHeading {
            get {
                return ResourceManager.GetString("SuggestionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Как переводится выражение?.
        /// </summary>
        public static string SuggestionTranslationDesctiption {
            get {
                return ResourceManager.GetString("SuggestionTranslationDesctiption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод.
        /// </summary>
        public static string Translation {
            get {
                return ResourceManager.GetString("Translation", resourceCulture);
            }
        }
    }
}
